using System;

[Flags]
public enum ENetPacketFlags : int
{
    None = 0,
    Reliable = 1,
    Unsequenced = 2,
    UnreliableFragment = 8
}

// Server sees messages from clients
public enum ClientMsg : byte
{
    CONNECTION_REQUEST,
    CLIENT_LOADED,
    PLAYER_INFO,
    CHANGE_PLAYER_NAME,
    CHANGE_PLAYER_NUMBER,
    CHANGE_PLAYER_TEAM,
    CHANGE_READY_STATUS,
    SEND_CONNECTING_PLAYER_INFO,
    CHAT_MESSAGE,
    INPUT,
}

// Client sees messages from server
public enum ServerMsg : byte
{
    CONNECTION_ACCEPTED,
    CONNECTION_DENIED,
    INITIAL_MATCH_STATE,
    PLAYER_JOINED,
    PLAYER_LEFT,
    RECEIVED_PLAYER_INFO,
    PLAYER_NAME_CHANGED,
    PLAYER_NUMBER_CHANGED,
    PLAYER_TEAM_CHANGED,
    PLAYER_READY_STATUS_CHANGED,
    SERVER_CLOSED,
    RECEIVED_CONNECTING_PLAYER_INFO,
    PLAYER_KICKED,
    BACKUP_NOMINATION,
    BACKUP_ASSIGNED,
    PLAYER_RESIGNED,
    ALL_PLAYERS_LOADED,
    START_GAME_COUNTDOWN,
    START_GAME,
    GAME_FINISHED,
    PLAYER_PING_UPDATE,
    GAME_PHASE_CHANGED,
    CHAT_MESSAGE,
}

public enum Msg : byte
{
    // SHARED PACKETS / P2P
    P2P_HOLE_PUNCH_REQUEST,
    P2P_HOLE_PUNCH_ACK,
    P2P_DISCONNECT,

    // SERVER PACKETS
    S2C_CONNECTION_ACCEPTED,
    S2C_CONNECTION_DENIED,
    S2C_INITIAL_MATCH_STATE, // <-- send match state after client signals ready
    S2C_PLAYER_JOINED,
    S2C_PLAYER_LEFT,
    S2C_RECEIVED_PLAYER_INFO,
    S2C_PLAYER_NAME_CHANGED,
    S2C_PLAYER_NUMBER_CHANGED,
    S2C_PLAYER_TEAM_CHANGED,
    S2C_PLAYER_READY_STATUS_CHANGED,

    S2C_SERVER_CLOSED,
    S2C_RECEIVED_CONNECTING_PLAYER_INFO,
    S2C_PLAYER_KICKED,
    S2C_BACKUP_NOMINATION,
    S2C_BACKUP_ASSIGNED,

    // SERVER ONLY
    S2C_PLAYER_RESIGNED,
    S2C_ALL_PLAYERS_LOADED,
    S2C_START_GAME_COUNTDOWN,
    S2C_START_GAME,
    S2C_GAME_FINISHED,
    S2C_PLAYER_PING_UPDATE,
    S2C_GAME_PHASE_CHANGED,

    // CLIENT PACKETS
    // Lobby
    C2S_CONNECTION_REQUEST,
    C2S_PLAYER_INFO,
    C2S_CHANGE_PLAYER_NAME,
    C2S_CHANGE_PLAYER_NUMBER,
    C2S_CHANGE_PLAYER_TEAM,
    C2S_CHANGE_READY_STATUS,
    C2S_SEND_CONNECTING_PLAYER_INFO,

    // **New handshake packet**
    C2S_CLIENT_LOADED, // client informs server they're loaded

    // Chat
    S2C_CHAT_MESSAGE,
    C2S_CHAT_MESSAGE,

    // Game
    C2S_INPUT,
    // C2S_SHOOT?

    S2C_PLAYER_SPAWNED,
}